[package]
name = "rolling_ohlc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
ordered-float = "2.0"
serde_json = "1.0"
lazy_static = "1.4"
approx = "0.5.1"
